/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane; // Untuk menampilkan pesan dialog
import java.util.Date; // Untuk mendapatkan tanggal
import java.text.ParseException;
import java.text.SimpleDateFormat;
import Controller.LaporanController;

/**
 *
 * @author EVA-01
 */
public class IsiLaporanWarga extends javax.swing.JFrame {
    private String nik; // Field untuk menyimpan NIK
    private LaporanController laporanController = new LaporanController();

    /**
     * Creates new form LoginMenu
     */
    public IsiLaporanWarga() {
        initComponents();
    }

    /**
     * Constructor dengan parameter NIK
     */
    public IsiLaporanWarga(String nik) {
        this.nik = nik;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboJenisLaporan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FormatTanggal = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        BtnSubmitLaporan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextDetail = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("WELCOME TO SISTEM LAPORAN DESA KONOHA");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Jenis Laporan");

        ComboJenisLaporan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ComboJenisLaporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kerusakan", "Pidana", "Kehilangan" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Detail");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Tanggal");

        try {
            javax.swing.text.MaskFormatter dateMask = new javax.swing.text.MaskFormatter("####-##-##");
            dateMask.setPlaceholderCharacter('_');
            FormatTanggal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(dateMask));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FormatTanggal.setToolTipText("Format: yyyy-MM-dd");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setText("yyyy-mm-dd");

        BtnSubmitLaporan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnSubmitLaporan.setText("Submit");
        BtnSubmitLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitLaporanActionPerformed(evt);
            }
        });

        JTextDetail.setColumns(20);
        JTextDetail.setRows(5);
        jScrollPane1.setViewportView(JTextDetail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1))
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addGap(91, 91, 91)
                                        .addComponent(jLabel9))
                                    .addComponent(FormatTanggal))
                                .addGap(767, 767, 767))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(jLabel4))
                                    .addComponent(BtnSubmitLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(ComboJenisLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboJenisLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FormatTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnSubmitLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addGap(89, 89, 89)
                .addComponent(jLabel4)
                .addGap(266, 266, 266))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FormatTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormatTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormatTanggalActionPerformed

    private void BtnSubmitLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitLaporanActionPerformed
        String jenisLaporan = (String) ComboJenisLaporan.getSelectedItem();
        String detailLaporan = JTextDetail.getText();
        String tanggalStr = FormatTanggal.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false);
        java.util.Date tanggalLaporan = null;
        boolean tanggalValid = true;
        try {
            tanggalLaporan = sdf.parse(tanggalStr);
        } catch (ParseException e) {
            tanggalValid = false;
        }
        // Validasi sederhana
        if (detailLaporan.trim().isEmpty() || tanggalStr.trim().isEmpty() || !tanggalValid) {
            JOptionPane.showMessageDialog(this,
                                        "Detail laporan dan tanggal tidak boleh kosong!\nFormat tanggal: yyyy-MM-dd",
                                        "Input Tidak Valid",
                                        JOptionPane.ERROR_MESSAGE);
            return; // Hentikan proses jika tidak valid
        }
        // Simpan ke database melalui controller
        boolean sukses = laporanController.submitLaporanBaru(
            nik,
            jenisLaporan,
            detailLaporan,
            tanggalStr,
            this
        );
        if (sukses) {
            // Kosongkan field setelah submit
            ComboJenisLaporan.setSelectedIndex(0);
            JTextDetail.setText("");
            FormatTanggal.setValue(null);
        }
    }//GEN-LAST:event_BtnSubmitLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IsiLaporanWarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IsiLaporanWarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IsiLaporanWarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IsiLaporanWarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IsiLaporanWarga("").setVisible(true); // Menggunakan constructor dengan parameter kosong
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSubmitLaporan;
    private javax.swing.JComboBox<String> ComboJenisLaporan;
    private javax.swing.JFormattedTextField FormatTanggal;
    private javax.swing.JTextArea JTextDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
