/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LaporanController;
import Model.Laporan;
import View.LoginPegawai;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;

/**
 *
 * @author EVA-01
 */
public class MenuPegawai extends javax.swing.JFrame {
    private LaporanController laporanController;
    private DefaultTableModel modelTabelLaporan;
    private TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form LoginMenu
     */
    public MenuPegawai() {
        initComponents();
        laporanController = new LaporanController();
        inisialisasiTabelModel();
        loadDataLaporan();
        sorter = new TableRowSorter<>(modelTabelLaporan);
        TabelLaporanDesa.setRowSorter(sorter);
        
        // Tambahkan event key pressed ke txtCariLaporan
        txtCariLaporan.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                // Jika key yang ditekan adalah Enter
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    btnCariLaporanActionPerformed(null);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelLaporanDesa = new javax.swing.JTable();
        txtCariLaporan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCariLaporan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ComboStatusLaporan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("WELCOME TO SISTEM LAPORAN DESA KONOHA");

        TabelLaporanDesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelLaporanDesa);

        jLabel2.setText("Cari Laporan");

        btnCariLaporan.setText("OK");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Status Laporan");

        ComboStatusLaporan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ComboStatusLaporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Dikerjakan", "Selesai" }));
        ComboStatusLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboStatusLaporanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnUpdate.setBackground(new java.awt.Color(255, 255, 102));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 0, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack1.setText("BACK");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCariLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(ComboStatusLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnBack1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCariLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboStatusLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack1)))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariLaporanActionPerformed(java.awt.event.ActionEvent evt) {                                               
        String searchNik = txtCariLaporan.getText().trim();
        if (searchNik.isEmpty()) {
            // Jika kotak pencarian kosong, tampilkan semua data
            sorter.setRowFilter(null);
        } else {
            try {
                // Buat filter yang hanya mencari di kolom NIK Pelapor (kolom indeks 1)
                RowFilter<DefaultTableModel, Object> nikFilter = RowFilter.regexFilter("(?i)" + searchNik, 1);
                sorter.setRowFilter(nikFilter);
                
                // Jika tidak ada hasil, beri tahu pengguna
                if (TabelLaporanDesa.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, 
                        "Tidak ditemukan laporan dengan NIK: " + searchNik, 
                        "Pencarian Tidak Ditemukan", 
                        JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (java.util.regex.PatternSyntaxException e) {
                // Jika pola regex tidak valid
                JOptionPane.showMessageDialog(this, 
                    "Format pencarian tidak valid", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
                sorter.setRowFilter(null);
            }
        }
    }  

    private void ComboStatusLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboStatusLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboStatusLaporanActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // Mendapatkan baris yang dipilih
        int selectedRow = TabelLaporanDesa.getSelectedRow();
        if (selectedRow == -1) {
            // Jika tidak ada baris yang dipilih
            JOptionPane.showMessageDialog(this, 
                "Pilih laporan yang ingin diupdate statusnya terlebih dahulu!", 
                "Tidak Ada Baris Dipilih", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Konversi indeks baris model jika tabel di-sort/filter
        int modelRow = TabelLaporanDesa.convertRowIndexToModel(selectedRow);
        
        // Mendapatkan ID Laporan dari baris yang dipilih (kolom 0)
        int idLaporan = Integer.parseInt(modelTabelLaporan.getValueAt(modelRow, 0).toString());
        
        // Mendapatkan status baru dari ComboBox
        String statusBaru = ComboStatusLaporan.getSelectedItem().toString();
        
        // Mendapatkan NIP pegawai yang login
        String nipPegawai = LoginPegawai.getNipPegawaiLogin();
        if (nipPegawai == null || nipPegawai.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "NIP Pegawai tidak diketahui. Mohon login ulang.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Konfirmasi update
        int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin mengubah status laporan ID " + idLaporan + " menjadi " + statusBaru + "?",
            "Konfirmasi Update Status",
            JOptionPane.YES_NO_OPTION);
            
        if (confirm == JOptionPane.YES_OPTION) {
            // Panggil controller untuk update status
            boolean berhasil = laporanController.prosesUpdateStatus(idLaporan, statusBaru, nipPegawai, this);
            
            if (berhasil) {
                // Update status di model tabel langsung tanpa meload ulang seluruh data
                // Ini akan mempertahankan tampilan tabel dan tidak "menghilangkan" tabel
                modelTabelLaporan.setValueAt(statusBaru, modelRow, 6); // Kolom 6 adalah Status
                
                // Update kolom pegawai penanggung jawab jika kosong sebelumnya
                if ("-".equals(modelTabelLaporan.getValueAt(modelRow, 7).toString())) {
                    modelTabelLaporan.setValueAt(nipPegawai, modelRow, 7); // Kolom 7 adalah Pgw Penjawab
                }
                
                // Update kolom tanggal update
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                String tanggalUpdateStr = sdf.format(new java.util.Date());
                modelTabelLaporan.setValueAt(tanggalUpdateStr, modelRow, 8); // Kolom 8 adalah Tgl Update
                
                // Tampilkan pesan sukses
                JOptionPane.showMessageDialog(this,
                    "Status laporan ID " + idLaporan + " berhasil diupdate menjadi " + statusBaru,
                    "Update Berhasil",
                    JOptionPane.INFORMATION_MESSAGE);
                
                // Pastikan baris tetap terpilih setelah update
                TabelLaporanDesa.setRowSelectionInterval(selectedRow, selectedRow);
            }
            // Jika gagal, pesan error sudah ditampilkan oleh controller
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = TabelLaporanDesa.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih laporan yang ingin dihapus terlebih dahulu!", "Tidak Ada Baris Dipilih", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int modelRow = TabelLaporanDesa.convertRowIndexToModel(selectedRow);
        int idLaporan = Integer.parseInt(modelTabelLaporan.getValueAt(modelRow, 0).toString());
        int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin menghapus laporan ID " + idLaporan + "?",
            "Konfirmasi Hapus Laporan",
            JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            boolean sukses = laporanController.hapusLaporan(idLaporan, this);
            if (sukses) {
                loadDataLaporan(); // Refresh tabel setelah hapus
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here
        LoginPegawai loginPegawaiForm = new LoginPegawai();
        loginPegawaiForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void inisialisasiTabelModel() {
        modelTabelLaporan = new DefaultTableModel(
            new Object[][] {},
            new String[] {"ID", "NIK Pelapor", "Jenis", "Detail", "Tgl Kejadian", "Tgl Lapor", "Status", "Pgw Penjawab", "Tgl Update"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        TabelLaporanDesa.setModel(modelTabelLaporan);
    }

    private void loadDataLaporan() {
        modelTabelLaporan.setRowCount(0);
        List<Laporan> daftarLaporan = laporanController.getListSemuaLaporan();

        for (Laporan lap : daftarLaporan) {
            String detailSingkat = lap.getDetail_laporan();
            if (detailSingkat != null && detailSingkat.length() > 50) {
                detailSingkat = detailSingkat.substring(0, 50) + "...";
            }
            modelTabelLaporan.addRow(new Object[]{
                lap.getId_laporan(),
                lap.getNik_pelapor(),
                lap.getJenis_laporan(),
                detailSingkat,
                lap.getTanggal_kejadian() != null ? lap.getTanggal_kejadian() : "-",
                lap.getTanggal_lapor() != null ? lap.getTanggal_lapor() : "-",
                lap.getStatus_laporan(),
                lap.getNip_pegawai_penanggung_jawab() != null ? lap.getNip_pegawai_penanggung_jawab() : "-",
                lap.getTanggal_update_status() != null ? lap.getTanggal_update_status() : "-"
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboStatusLaporan;
    private javax.swing.JTable TabelLaporanDesa;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnCariLaporan;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCariLaporan;
    // End of variables declaration//GEN-END:variables
}
